# ODE docker-compose file for development environment
# 2019 Project-ODE

version: '3.5'
services:
  testdb:
    image: mdillon/postgis
    environment:
      - POSTGRES_USER=test
    networks:
      - db

  feature_service:
    build: FeatureService
    depends_on:
      - testdb
    ports:
      - "7231:7231"
    environment:
      - NODE_ENV=test
    command: bash -c "sleep 5; knex migrate:latest && knex seed:run && npm start"
    networks:
      - db

networks:
  db:
