#!/bin/bash

token=`curl --data "username=Maelle&password=YhmAt*X2k@RJ02H8" localhost:7231/data.ode.org/v1/authentication/authenticate | tr -d '"}' | cut -c 8-`;

curl 'http://localhost:7231/data.ode.org/v1/annotation-campaign/new' -H "Authorization: Bearer $token" -H 'Content-Type: application/json' --data '{"name":"Campagne D-calls","desc":"Les enregistrements à annoter datent de 2010, 2012 et 2016 et viennent des sites NCRO, MAD et WKER du réseau d\u0027hydrophones OHASISBIO. Les vocalises à annoter sur ce jeu de données sont les sons sociaux des baleines bleues, appelés D-calls. Ces sons sont modulés des hautes fréquences (~90 Hz) au plus basses fréquences (~30Hz) et durent de 1 à 8 secondes environ.","datasets":[1],"start":"2018-10-01","end":"2018-12-01","annotation_set":1,"annotators":[1,2,3,4],"annotation_goal":4,"annotation_method":1}';

curl 'http://localhost:7231/data.ode.org/v1/annotation-campaign/new' -H "Authorization: Bearer $token" -H 'Content-Type: application/json' --data '{"name":"Campagne MAD-calls","desc":"Les enregistrements datent de 2015 et proviennent des sites MAD, NEAMS et WKER du réseau d\u0027hydrophones OHASISBIO. La vocalise à annoter sur ce jeu de données est l\u0027unité 1 des cris de baleines bleues pygmées de Madagascar. Cette vocalisation est centrée autour de 35 Hz et dure environ 15 secondes.","datasets":[2],"start":"2018-10-01","end":"2018-12-01","annotation_set":2,"annotators":[1,2,3,4],"annotation_goal":4,"annotation_method":1}';

curl 'http://localhost:7231/data.ode.org/v1/annotation-campaign/new' -H "Authorization: Bearer $token" -H 'Content-Type: application/json' --data '{"name":"Campagne AUS-calls","desc":"Les enregistrements datent de 2015 et proviennent des sites NEAMS et WKER du réseau d\u0027hydrophones OHASISBIO. La vocalise à annoter sur ce jeu de données est l\u0027unité 2 des cris de baleines bleues pygmées d\u0027Australie. Cette vocalisation est centrée autour de 70 Hz et dure environ 23 secondes.","datasets":[3],"start":"2018-10-01","end":"2018-12-01","annotation_set":3,"annotators":[1,2,3,4],"annotation_goal":4,"annotation_method":1}';
